### ISSUE TITLE
Adding Flattr

### ISSUE THREAD

**Issue by mihagazvoda** [koaning/thismonth.rocks#38]
I would like to add [Flattr](flattr.com) somewhere. Maybe Tech Cleanup? What do you think?

**Comment by koaning** [comment]
I am unfamiliar with the platform. Is it similar to patreon?

**Comment by mihagazvoda** [comment]
Kind of. You pay a monthly fee that gets distributed among creators (websites) you support. Proportions (number of Flattrs) are based on time spent on the website or by giving Flattrs directly. 
It doesn't seem to work properly - Flattrs aren't tracked and you can only choose to support among featured (~50) websites.  
I wrote to them about the issue and I'm waiting for their response. I'll close the issue within a few days if they don't respond.
